SrcApplications As screen:
    OnVisible: =

    CtnBody As groupContainer.verticalAutoLayoutContainer:
        Height: =Parent.Height
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =2

        ctnHeader As groupContainer.horizontalAutoLayoutContainer:
            DropShadow: =DropShadow.Semibold
            Fill: =RGBA(39, 113, 194, 1)
            FillPortions: =0
            Height: =80
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingBottom: =20
            PaddingLeft: =20
            PaddingTop: =20
            ZIndex: =1

            lblTitle As label:
                AutoHeight: =true
                Color: =RGBA(255, 255, 255, 1)
                Font: =Font.'Segoe UI'
                FontWeight: =FontWeight.Semibold
                Height: =50
                Size: =24
                Text: ="Contoso University - Application"
                Width: =600
                ZIndex: =1

            ctnHeaderMenu As groupContainer.horizontalAutoLayoutContainer:
                LayoutGap: =10
                LayoutJustifyContent: =LayoutJustifyContent.End
                LayoutMinHeight: =40
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                PaddingLeft: =20
                PaddingRight: =20
                ZIndex: =2

                icoApplication As icon.Phonebook:
                    Color: =RGBA(255, 255, 255, 1)
                    Height: =40
                    Icon: =Icon.DocumentWithContent
                    OnSelect: =Navigate(SrcApplications);
                    Width: =40
                    ZIndex: =1

                icoDepartment As icon.OfficeBuilding:
                    Color: =RGBA(255, 255, 255, 1)
                    Height: =40
                    Icon: =Icon.OfficeBuilding
                    OnSelect: =Navigate(SrcDepartments);
                    Width: =40
                    ZIndex: =2

                icoSemester As icon.CalendarBlank:
                    Color: =RGBA(255, 255, 255, 1)
                    Height: =40
                    Icon: =Icon.CalendarBlank
                    Width: =40
                    ZIndex: =3

                icoContact As icon.Phonebook:
                    Color: =RGBA(255, 255, 255, 1)
                    Height: =40
                    Icon: =Icon.Phonebook
                    Width: =40
                    ZIndex: =4

        CtnMain As groupContainer.horizontalAutoLayoutContainer:
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            ZIndex: =2

            CtnMainLeft As groupContainer.horizontalAutoLayoutContainer:
                FillPortions: =0
                LayoutDirection: =LayoutDirection.Vertical
                LayoutMinHeight: =100
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                PaddingBottom: =20
                PaddingLeft: =20
                PaddingTop: =20
                Width: =400
                ZIndex: =1

                CtnMainLeftMenu As groupContainer.horizontalAutoLayoutContainer:
                    FillPortions: =0
                    Height: =80
                    LayoutMinHeight: =100
                    LayoutMinWidth: =250
                    LayoutMode: =LayoutMode.Auto
                    PaddingLeft: =10
                    PaddingRight: =10
                    ZIndex: =1

                    icoAddApplication As icon.Add:
                        Height: =42
                        Icon: =Icon.Add
                        OnSelect: =NewForm(frmApplication)
                        Width: =42
                        ZIndex: =1

                "glyApplications As gallery.'BrowseLayout_Vertical_TwoTextOneImageVariant_ver5.0'":
                    DelayItemLoading: =true
                    Items: =Applications
                    Layout: =Layout.Vertical
                    LayoutMinHeight: =287
                    LayoutMinWidth: =320
                    LoadingSpinner: =LoadingSpinner.Data
                    OnSelect: =EditForm(frmApplication)
                    ShowNavigation: =true
                    TemplatePadding: =0
                    TemplateSize: =104
                    X: =488
                    Y: =132
                    ZIndex: =2

                    Image1 As image:
                        Height: =72
                        OnSelect: =Select(Parent)
                        RadiusBottomLeft: =8
                        RadiusBottomRight: =8
                        RadiusTopLeft: =8
                        RadiusTopRight: =8
                        Width: =72
                        X: =16
                        Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
                        ZIndex: =1

                    Title1 As label:
                        FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                        Height: =Self.Size * 1.8
                        OnSelect: =Select(Parent)
                        PaddingBottom: =0
                        PaddingLeft: =0
                        PaddingRight: =0
                        PaddingTop: =0
                        Text: =ThisItem.Name
                        VerticalAlign: =VerticalAlign.Top
                        Width: =Parent.TemplateWidth - 173
                        X: =103
                        Y: =(Parent.TemplateHeight - (Self.Size * 1.8 + Subtitle1.Size * 1.8)) / 2
                        ZIndex: =2

                    Subtitle1 As label:
                        FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                        Height: =Self.Size * 1.8
                        OnSelect: =Select(Parent)
                        PaddingBottom: =0
                        PaddingLeft: =0
                        PaddingRight: =0
                        PaddingTop: =0
                        Text: =ThisItem.'Created On'
                        VerticalAlign: =VerticalAlign.Top
                        Width: =Title1.Width
                        X: =Title1.X
                        Y: =Title1.Y + Title1.Height
                        ZIndex: =3

                    NextArrow1 As icon.ChevronRight:
                        AccessibleLabel: =Self.Tooltip
                        Color: =RGBA(166, 166, 166, 1)
                        Height: =50
                        Icon: =Icon.ChevronRight
                        OnSelect: =Select(Parent)
                        PaddingBottom: =16
                        PaddingLeft: =16
                        PaddingRight: =16
                        PaddingTop: =16
                        Tooltip: ="View item details"
                        Width: =50
                        X: =Parent.TemplateWidth - Self.Width - 12
                        Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
                        ZIndex: =4

                    Separator1 As rectangle:
                        Fill: =RGBA(255, 255, 255, 1)
                        Height: =8
                        OnSelect: =Select(Parent)
                        Width: =Parent.TemplateWidth
                        Y: =Parent.TemplateHeight - Self.Height
                        ZIndex: =5

                    Rectangle1 As rectangle:
                        Height: =Parent.TemplateHeight - Separator1.Height
                        OnSelect: =Select(Parent)
                        Visible: =ThisItem.IsSelected
                        Width: =4
                        ZIndex: =6

            CtnMainRight As groupContainer.horizontalAutoLayoutContainer:
                LayoutMinHeight: =100
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                PaddingBottom: =20
                PaddingLeft: =20
                PaddingRight: =20
                PaddingTop: =20
                Width: =400
                ZIndex: =2

                frmApplication As form:
                    DataSource: =Applications
                    Item: =glyApplications.Selected
                    LayoutMinHeight: =250
                    LayoutMinWidth: =400
                    NumberOfColumns: =2
                    ZIndex: =1

                    Applicant_DataCard1 As typedDataCard.comboBoxEditCard:
                        BorderStyle: =BorderStyle.Solid
                        DataField: ="cu_applicant_id"
                        Default: =ThisItem.Applicant
                        DisplayMode: =Parent.DisplayMode
                        DisplayName: =DataSourceInfo([@Applications],DataSourceInfo.DisplayName,"cu_applicant_id")
                        Fill: =RGBA(0, 0, 0, 0)
                        Height: =50
                        Required: =false
                        Update: =DataCardValue3.Selected
                        Width: =463
                        X: =0
                        Y: =1
                        ZIndex: =1

                        DataCardKey3 As label:
                            AutoHeight: =true
                            Height: =34
                            Text: =Parent.DisplayName
                            Width: =Parent.Width - 60
                            Wrap: =false
                            X: =30
                            Y: =10
                            ZIndex: =1

                        DataCardValue3 As combobox:
                            BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                            DefaultSelectedItems: =Parent.Default
                            DisplayFields: =["fullname"]
                            DisplayMode: =Parent.DisplayMode
                            Items: =Choices([@Applications].cu_applicant_id)
                            PaddingLeft: =If(Self.DisplayMode = DisplayMode.Edit, 5, 0)
                            SearchFields: =["fullname"]
                            SearchItems: =Search(Choices([@Applications].cu_applicant_id),DataCardValue3.SearchText,"fullname")
                            SelectMultiple: =false
                            Tooltip: =Parent.DisplayName
                            Width: =Parent.Width - 60
                            X: =30
                            Y: =DataCardKey3.Y + DataCardKey3.Height + 5
                            ZIndex: =2

                        ErrorMessage2 As label:
                            AutoHeight: =true
                            Height: =10
                            Live: =Live.Assertive
                            PaddingBottom: =0
                            PaddingLeft: =0
                            PaddingRight: =0
                            PaddingTop: =0
                            Text: =Parent.Error
                            Visible: =Parent.DisplayMode=DisplayMode.Edit
                            Width: =Parent.Width - 60
                            X: =30
                            Y: =DataCardValue3.Y + DataCardValue3.Height
                            ZIndex: =3

                        StarVisible2 As label:
                            Align: =Align.Center
                            Height: =DataCardKey3.Height
                            Text: ="*"
                            Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                            Width: =30
                            Wrap: =false
                            Y: =DataCardKey3.Y
                            ZIndex: =4

                    Department_DataCard1 As typedDataCard.comboBoxEditCard:
                        BorderStyle: =BorderStyle.Solid
                        DataField: ="cu_department_id"
                        Default: =ThisItem.Department
                        DisplayMode: =Parent.DisplayMode
                        DisplayName: =DataSourceInfo([@Applications],DataSourceInfo.DisplayName,"cu_department_id")
                        Fill: =RGBA(0, 0, 0, 0)
                        Height: =50
                        Required: =false
                        Update: =DataCardValue4.Selected
                        Width: =463
                        X: =1
                        Y: =1
                        ZIndex: =1

                        DataCardKey4 As label:
                            AutoHeight: =true
                            Height: =34
                            Text: =Parent.DisplayName
                            Width: =Parent.Width - 60
                            Wrap: =false
                            X: =30
                            Y: =10
                            ZIndex: =1

                        DataCardValue4 As combobox:
                            BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                            DefaultSelectedItems: =Parent.Default
                            DisplayFields: =["cu_name"]
                            DisplayMode: =Parent.DisplayMode
                            Items: =Choices([@Applications].cu_department_id)
                            PaddingLeft: =If(Self.DisplayMode = DisplayMode.Edit, 5, 0)
                            SearchFields: =["cu_name"]
                            SearchItems: =Search(Choices([@Applications].cu_department_id),DataCardValue4.SearchText,"cu_name")
                            SelectMultiple: =false
                            Tooltip: =Parent.DisplayName
                            Width: =Parent.Width - 60
                            X: =30
                            Y: =DataCardKey4.Y + DataCardKey4.Height + 5
                            ZIndex: =2

                        ErrorMessage3 As label:
                            AutoHeight: =true
                            Height: =10
                            Live: =Live.Assertive
                            PaddingBottom: =0
                            PaddingLeft: =0
                            PaddingRight: =0
                            PaddingTop: =0
                            Text: =Parent.Error
                            Visible: =Parent.DisplayMode=DisplayMode.Edit
                            Width: =Parent.Width - 60
                            X: =30
                            Y: =DataCardValue4.Y + DataCardValue4.Height
                            ZIndex: =3

                        StarVisible3 As label:
                            Align: =Align.Center
                            Height: =DataCardKey4.Height
                            Text: ="*"
                            Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                            Width: =30
                            Wrap: =false
                            Y: =DataCardKey4.Y
                            ZIndex: =4

                    Name_DataCard1 As typedDataCard.textualEditCard:
                        BorderStyle: =BorderStyle.Solid
                        DataField: ="cu_name"
                        Default: =ThisItem.Name
                        DisplayMode: =Parent.DisplayMode
                        DisplayName: =DataSourceInfo([@Applications],DataSourceInfo.DisplayName,"cu_name")
                        Fill: =RGBA(0, 0, 0, 0)
                        Height: =50
                        MaxLength: =DataSourceInfo([@Applications], DataSourceInfo.MaxLength, "cu_name")
                        Required: =true
                        Update: =DataCardValue1.Text
                        Width: =926
                        X: =0
                        Y: =0
                        ZIndex: =2

                        DataCardKey1 As label:
                            AutoHeight: =true
                            Height: =34
                            Text: =Parent.DisplayName
                            Width: =Parent.Width - 60
                            Wrap: =false
                            X: =30
                            Y: =10
                            ZIndex: =1

                        DataCardValue1 As text:
                            BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                            Default: =Parent.Default
                            DelayOutput: =true
                            DisplayMode: =Parent.DisplayMode
                            MaxLength: =Parent.MaxLength
                            PaddingLeft: =5
                            RadiusBottomLeft: =0
                            RadiusBottomRight: =0
                            RadiusTopLeft: =0
                            RadiusTopRight: =0
                            Tooltip: =Parent.DisplayName
                            Width: =Parent.Width - 60
                            X: =30
                            Y: =DataCardKey1.Y + DataCardKey1.Height + 5
                            ZIndex: =2

                        ErrorMessage1 As label:
                            AutoHeight: =true
                            Height: =10
                            Live: =Live.Assertive
                            PaddingBottom: =0
                            PaddingLeft: =0
                            PaddingRight: =0
                            PaddingTop: =0
                            Text: =Parent.Error
                            Visible: =Parent.DisplayMode=DisplayMode.Edit
                            Width: =Parent.Width - 60
                            X: =30
                            Y: =DataCardValue1.Y + DataCardValue1.Height
                            ZIndex: =3

                        StarVisible1 As label:
                            Align: =Align.Center
                            Height: =DataCardKey1.Height
                            Text: ="*"
                            Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                            Width: =30
                            Wrap: =false
                            Y: =DataCardKey1.Y
                            ZIndex: =4

                    "'Created On_DataCard1' As typedDataCard.textualViewCard":
                        BorderStyle: =BorderStyle.Solid
                        DataField: ="createdon"
                        Default: =ThisItem.'Created On'
                        DisplayMode: =DisplayMode.View
                        DisplayName: =DataSourceInfo([@Applications],DataSourceInfo.DisplayName,"createdon")
                        Fill: =RGBA(0, 0, 0, 0)
                        Height: =40
                        Required: =false
                        Width: =463
                        X: =0
                        Y: =2
                        ZIndex: =2

                        DataCardKey2 As label:
                            AutoHeight: =true
                            Height: =34
                            Text: =Parent.DisplayName
                            Width: =Parent.Width - 60
                            Wrap: =false
                            X: =30
                            Y: =10
                            ZIndex: =1

                        DataCardValue2 As label:
                            AutoHeight: =true
                            DisplayMode: =Parent.DisplayMode
                            Height: =27
                            PaddingLeft: =0
                            PaddingRight: =0
                            PaddingTop: =0
                            Text: =Parent.Default
                            Width: =Parent.Width - 60
                            X: =30
                            Y: =DataCardKey2.Y + DataCardKey2.Height + 5
                            ZIndex: =2

