# Workflow to download and import Contoso_university_core solution to an environment using Service Principal
name: Deploy Contoso_university_core Demo

# trigger on workflow based on Pack Contoso_University_Core Demo workflow completion
on:
    workflow_run:
        workflows: ["Pack Contoso_University_Core Demo"]
        branches: [main]
        types:
            - completed
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        environment: dev-demo
        steps:
            - name: Download Artifact 
              uses: dawidd6/action-download-artifact@v2
              with:
                workflow: pack-contoso-university-core-demo.yml
                name: packed-solution
            - name: Install Power Platform Tool
              uses: microsoft/powerplatform-actions/actions-install@v1.2.0
            - name: Import Contoso_university_Core
              uses: microsoft/powerplatform-actions/import-solution@v1.2.0
              with:
                environment-url: ${{ env.ORGURL }}
                app-id: ${{ secrets.Appid }}
                client-secret: ${{ secrets.secret }}
                tenant-id: ${{ secrets.tenantid }}
                solution-file: contoso_university_core_managed.zip
